apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rosa-jboss
  namespace: openshift-gitops
spec:
  destination:
    namespace: rosa-jboss
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/marcoklaassen/rosa-jboss-demo.git'
    path: gitops
  project: default
